import './modules/modals.js';
import './modules/forms.js';
import './modules/masks.js';
import './modules/spinner.js';
import './modules/scroll.js';
import './modules/menus.js';
import './modules/tabs.js';
import './modules/galleries.js';
import './modules/rotators.js';
